version: "3.5"
services:
  rabbitmq:
    image: "rabbitmq:3-management"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks: 
      - quizrt-message-broker-network
    # volumes:
    #   - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
networks: 
  quizrt-message-broker-network:
    name: quizrt-network
    external: true